### ISSUE TITLE
[sync] full sync does not complete

### ISSUE THREAD

**Issue by rgeraldes** [kowala-tech/kUSD#105]
### _Type_:
Issue

### _What happened? / What do you need?_:
The full sync does not complete as soon as we have a decent number of blocks in the network.

### _If it's an issue, how can we reproduce it?_:
Connect a full node (ex: faucet) to the current testnet using the full sync mode.

### _Affected servers or services_:
Faucet & non genesis validators using the full sync.

### _Priority_:
High

**Comment by yourheropaul** [comment]
I've marked this as high priority, because it could be a fairly serious problem.

How will we make the full sync work?
