### ISSUE TITLE
[consensus] Complete the proposal mechanism.

### ISSUE THREAD

**Issue by rgeraldes** [kowala-tech/kUSD#32]
- The current model selects the first validator as the proposer.

**Comment by yourheropaul** [comment]
The proposer should be elected with the following constraints:

- [ ] The 'weight'<sup id="a1">[1](#f1)</sup> of a potential validator in the election should be proportional to the number of tokens they are staking<sup id="a2">[2](#f2)</sup>.
- [ ] Validators are only eligible for election if they:
  - [ ] (1) Validated or were the proposer in the previous block, and
  - [ ] (2) Are staking with more >= the current minimum number of tokens<sup id="a3">[3](#f3)</sup>
- [ ] If there are < 6 validators that meet the conditions above, then all valdiators are eligible for proposer election

---

<em id="f1">1. As in, the number of votes in the PBFT election cycle. A validator with more weight is more likely to be elected than a valdiator with less weight. [↩](#a1)

<em id="f2">2. Miners may stake tokens that they don't own, if the owner has delegated them. This should be looked up in the Network contract. See #27. [↩](#a2)

<em id="f3">3. The minimum number of required tokens will change as the network grows. Mechanism TBD. [↩](#a3)

**Comment by yourheropaul** [comment]
There's also a need for peer connection management (for if we change voters during a round).

**Comment by yourheropaul** [comment]
I've updated the comment above to include the final requirements for Andromeda.

**Comment by rgeraldes** [comment]
Validators are only eligible for election if they:
 (1) Validated or were the proposer in 50% of the last 10,000 blocks

@yourheropaul how do we add new validators given this condition?
