### ISSUE TITLE
Merge code into dev and master

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kUSD#37]
In order to start testing (and building in DockerHub) we need to merge to code. Are we ready for this?

**Comment by yourheropaul** [comment]
This should include all pull requests

**Comment by yourheropaul** [comment]
This blocks other work, so I've added a tag,

**Comment by acroca** [comment]
We're now using dev and I guess will merge to master as soon as we reach a stable state, so I feel this can be closed, right?
