### ISSUE TITLE
[testnet] Coin faucet

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kUSD#48]
We need to let testnet users get initial funds for testing. For that we can use a faucet.

Ethererum has one: https://github.com/kowala-tech/kUSD/projects/1

and there's https://faucet.rinkeby.iom which uses social media.

**Comment by rgeraldes** [comment]
I had a look at the client (cmd/faucet) and the work consists in using a full node instead of a light client since we have not implemented a light client for PoS yet.
