### ISSUE TITLE
Validation starts even without the --validate option

### ISSUE THREAD

**Issue by acroca** [kowala-tech/kUSD#55]
I have a node mining blocks and when I connect a 2nd node to it, it synchronizes and tries to start validating, but it doesn't have the `--validate` option.

**Comment by rgeraldes** [comment]
I had a look at the code and removing the following switch case from the validator is enough:
case downloader.StartEvent:
			atomic.StoreInt32(&val.shouldStart, 1)
In Pow this event is relevant but in POS is not since the voting always start after the sync has been done and it's not ok to interrupt the voting to sync.

**Comment by acroca** [comment]
I'm running into the issue again running two validators:
- Run validator 1
- Let validator 1 mine for a bit
- Run validator 2

Expected: Validator 2 syncs and and joins validation
Happening: Validator 2 syncs up but doesn't validate. It also doesn't sync new blocks.
