### ISSUE TITLE
Assign relevant settings for the `--testnet` flag

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kUSD#84]
It should be possible to run `kusd --testnet [flags...]`, such that the default values of all relevant flags will point at the testnet.

**Comment by rgeraldes** [comment]
The current flags covered are:
- datadir: "testnet"
- bootnodes: the current ones.
- networkid: 3
- default genesis block: we need to assemble the final genesis block.

The kusd init command is not going to be necessary if we provide a specific genesis block.
Let me know if you'd like other values for the fields above @acroca  @yourheropaul

**Comment by acroca** [comment]
I don't think we need to set any datadir if we ship docker containers, using the default one should be fine. But if we want to support non-docker setups then it's a good idea to separate it from mainnet.
