### ISSUE TITLE
[docker] Make init optional

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kUSD#85]
When running the docker image, the `kusd init path/to/genesis.json` should be explicitly required. Currently it always runs. 

Ideally this would be specified by a `--init` flag.

**Comment by acroca** [comment]
In which situations is the init unnecessary?

**Comment by yourheropaul** [comment]
I've realised that initialising an existing chain doesn't overwrite anything. For some reason, when I wrote this ticket, I didn't think about that. Closing this.
