### ISSUE TITLE
[testnet] Add dashboard

### ISSUE THREAD

**Issue by yourheropaul** [kowala-tech/kUSD#86]
The dashboard should be part of the testnet cluster. There may be a manual step configuring the DNS, but that seems acceptable.

There's a dockerised version of the Kowala-flavoured netstats: https://hub.docker.com/r/kowalatech/netstats.

(Not that netstats requires a secret key to be configured at runtime; see DockerHub description).

**Comment by acroca** [comment]
Only pending to update dns and all stats address to point to the new one.
