### ISSUE TITLE
[testnet] add a wallet

### ISSUE THREAD

**Issue by rgeraldes** [kowala-tech/kUSD#90]
### _Type_:
Request

### _What do you need?_:
We should include a wallet (user friendly UI)

### _Priority_:
High

### _Other info we may need_:
The latest version of go-ethereum contains a set of docker files with the wallet setup.
https://github.com/ethereum/go-ethereum/blob/master/cmd/puppeth/module_wallet.go

**Comment by acroca** [comment]
We're running a fork of MyEtherWallet now.
